covidapi/urls.py
from django.contrib import admin
from django.urls import path, include

from frontend.views import update_graph

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('update_bd/', update_graph, name='update')
]

frontend/urls.py
from django.urls import path,register_converter
from frontend.views import Home, Simulation, Diagnose, predict, result_predict, vote, result_vote
from frontend.utils import FloatConverter

register_converter(FloatConverter, 'float')
app_name = 'frontend'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('simulation', Simulation.as_view(), name='simulation'),
    path('diagnose', Diagnose.as_view(), name='diagnose'),
    path('vote', vote, name='vote'),
    path('<int:question_id>/<int:question_id2>/vote', result_vote, name='result_vote'),
    path('predict', predict, name='predict'),
    path('<float:question_id1>/<float:question_id2>/<float:question_id3>/<float:question_id4>/<float:question_id5>/'
         '<float:question_id6>/<float:question_id7>/<float:question_id8>/<float:question_id9>/<float:question_id10>/'
         '<float:question_id11>/<float:question_id12>/<float:question_id13>/<float:question_id14>/'
         '<float:question_id15>/predict', result_predict, name='result_predict'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

frontend/views.py
import pytz
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import pandas as pd

# Create your views here.
from django.urls import reverse

from django.views.generic import TemplateView

from api.models import ConfirmedData, DeadData, RecoveredData, CovidData, \
    ImportsUpdate
from api.tasks import update_database
from frontend.utils import plotlinechart, curva_evolucao_confirmados, \
    plot_curva_evolucao_confirmados, progressao_confirmados, \
    plot_progressao_confirmados, acumulo_progressao_confirmados, \
    plot_acumulo_progressao_confirmados, projecao_brasil, plot_projecao_brasil, \
    plot_curva_log_confirmados_brasil, curva_log_confirmados_mundo, \
    plot_curva_log_confirmados_mundo, curva_log_confirmados_brasil, \
    trata_base_Einstein, \
    feature_importance_Einstein, predict_Einstein, predict_Einstein2, \
    triple_graph, plot_triple_graph

from .forms import NameForm

def update_graph(request):
    update_database()
    return HttpResponse('updated')


class Home(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)

        conf = ConfirmedData.objects.all().values('country', 'count', 'timestamp')
        dead = DeadData.objects.all().values('country', 'count',
                                             'timestamp')
        recovered = RecoveredData.objects.all().values('country', 'count', 'timestamp')

        states_data = CovidData.objects.all().values(
            'country', 'state', 'deaths', 'new_deaths', 'total_cases',
            'new_cases', 'timestamp'
        )

        last_updated = None
        try:
            last_updated = ImportsUpdate.objects.latest(
                'created_at').created_at
        except ConfirmedData.DoesNotExist:
            print('Empty database')

        df_conf = pd.DataFrame.from_records(conf, index='timestamp')
        df_dead = pd.DataFrame.from_records(dead, index='timestamp')
        df_recovered = pd.DataFrame.from_records(recovered, index='timestamp')
        df_br_states = pd.DataFrame.from_records(states_data, index='timestamp')

        lista_paises = ['Australia', 'Iran', 'Italy', 'Japan', 'Korea, South',
                        'Spain', 'United Kingdom', 'US', 'Netherlands',
                        'Norway', 'Brazil', 'China']

        lista_paises2 = ['Italy', 'China', 'Korea, South']

        dados_paises = pd.DataFrame(data={
            'Country/Region': ['Australia', 'Brazil', 'Iran', 'Italy', 'Japan',
                               'Korea, South', 'Netherlands', 'Norway',
                               'Spain', 'US', 'United Kingdom', 'China'],
            'Color': ['rgb(67, 207, 246)', 'rgb(255, 90, 67)',
                      'rgb(230, 220, 215)', 'rgb(230, 220, 215)',
                      'rgb(230, 220, 215)', 'rgb(230, 220, 215)',
                      'rgb(255, 142, 46)', 'rgb(0, 151, 150)',
                      'rgb(230, 220, 215)', 'rgb(153, 213, 213)',
                      'rgb(230, 220, 215)', 'rgb(114,34,130)'],
            'Width': [4, 4, 2, 2, 2, 2, 4, 4, 2, 4, 2, 4],
            'Order': [11, 12, 1, 2, 3, 4, 8, 9, 6, 7, 5, 10]})

        dados_graf_1 = curva_evolucao_confirmados(df_conf, lista_paises)

        plot_1 = plot_curva_evolucao_confirmados(dados_graf_1, dados_paises,
                                                 plot_china=1)

        dados_graf_2 = progressao_confirmados(df_conf, lista_paises)

        plot_2 = plot_progressao_confirmados(dados_graf_2, dados_paises, 1)

        dados_graf_3 = acumulo_progressao_confirmados(df_conf, lista_paises)

        plot_3 = plot_acumulo_progressao_confirmados(dados_graf_3,
                                                     dados_paises, 1)

        dados_graf_4 = projecao_brasil(df_conf, lista_paises, lista_paises2)

        plot_4 = plot_projecao_brasil(dados_graf_4, dados_paises, 1)

        df_plot5 = curva_log_confirmados_mundo(df_conf,lista_paises)

        plot_5 = plot_curva_log_confirmados_mundo(df_plot5,lista_paises)

        df_plot6 = curva_log_confirmados_brasil(df_br_states, [])

        plot_6 = plot_curva_log_confirmados_brasil(df_plot6, [])

        dados_graf_7 = triple_graph(df_conf, df_dead, df_recovered)

        plot_7 = plot_triple_graph(dados_graf_7)

        context.update({
            'chart_1': plot_1,
            'chart_2': plot_2,
            'chart_3': plot_3,
            'chart_4': plot_4,
            'chart_5': plot_5,
            'chart_6': plot_6,
            'chart_7': plot_7,
            'last_update': last_updated
        })

        return context


class Simulation(TemplateView):
    template_name = "simulation.html"

class Diagnose(TemplateView):
    template_name = "diagnose.html"

    def get_context_data(self, **kwargs):
        context = super(Diagnose, self).get_context_data(**kwargs)

        base = trata_base_Einstein(0)

        ft_import = feature_importance_Einstein(base)

        pred = predict_Einstein(ft_import)


        context.update({
            'top15': ft_import['top15'],
            'acuracia': pred['acuracia'],
            'modelo_ft_import': ft_import['model'],
            'modelo_mlpc': pred['param_mlpc'],
            'dados_neg': pred['dados_neg'],
            'result_neg': pred['result_neg'],
            'dados_pos': pred['dados_pos'],
            'result_pos': pred['result_pos'],
            'top15_names': ft_import['top15_names'],
        })

        return context

def vote(request):
    if request.method == "POST":
        question = request.POST.get('question_id',999)
        question2 = request.POST.get('question_id2', 999)
    return HttpResponseRedirect(reverse('frontend:result_vote',args=[question,question2]))

def result_vote(request, question_id, question_id2):

    result = int(question_id) + int(question_id2)
    return HttpResponse(str(question_id)+"  "+str(question_id2)+"   "+str(result))

def predict(request):
    if request.method == "POST":
        lista_pred=[]
        for i in range(15):
            lista_pred.append(request.POST.get('question_id'+str(i+1),999))
    return HttpResponseRedirect(reverse('frontend:result_predict',args=[lista_pred[0],lista_pred[1],lista_pred[2],
                                                                        lista_pred[3],lista_pred[4],lista_pred[5],
                                                                        lista_pred[6],lista_pred[7],lista_pred[8],
                                                                        lista_pred[9],lista_pred[10],lista_pred[11],
                                                                        lista_pred[12],lista_pred[13],lista_pred[14]]))

def result_predict(request,question_id1,question_id2,question_id3,question_id4,question_id5,
                   question_id6,question_id7,question_id8,question_id9,question_id10,
                   question_id11,question_id12,question_id13,question_id14,question_id15):

    lista_pred=[question_id1,question_id2,question_id3,question_id4,question_id5,question_id6,question_id7,
                question_id8,question_id9,question_id10,question_id11,question_id12,question_id13,
                question_id14,question_id15]

    base = trata_base_Einstein(0)

    ft_import = feature_importance_Einstein(base)

    pred = predict_Einstein2(ft_import,lista_pred)

    return HttpResponse("Seu resultado é: <strong>"+str(pred['result'])+"</strong><br>com uma precisão de: <strong>"+
                        str(pred['acuracia'])+"%</strong><br><br>Teste positivo = "+str(pred['result_pos'])+
                        "<br>Teste negativo = "+str(pred['result_neg'])+
                        "<br><br>Se os testes acima não derem POSITIVO e NEGATIVO, respectivamente, pressione "+
                        "<strong>f5</strong> para um novo treinamento da rede neural.")

frontend/templates/diagnose.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
  <!--<meta charset="UTF-8">-->
  <title>COVID19 DIAGNOSE</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<style>
div.sticky {
  position: -webkit-sticky;
  position: sticky;
  top: 0;
  background-color: yellow;
}
  .button2 {
  font: bold 32px Arial;
  text-decoration: none;
  background-color: rgba(200,180,120,0.7);
  color: #333333;
  padding: 2px 6px 2px 6px;
  border-top: 1px solid #CCCCCC;
  border-right: 1px solid #333333;
  border-bottom: 1px solid #333333;
  border-left: 1px solid #CCCCCC;
}
</style>

<body style="background: url(../images/covid19.jpeg) no-repeat center center fixed;">

<div class="container p-3 my-3 border">

   <div style="text-align:center">
    <a class="button2" href="/">Página Inicial</a>
    <a class="button2" href="/diagnose">Diagnóstico COVID</a>
    <a class="button2" href="/simulation">Simulador Contágio</a>
  </div>

  <h4 style="text-align:justify"><strong style="color:red">IMPORTANTE: Esta solução é uma aproximação matemática e não garante a certeza
  da existência de qualquer doença.Para a certeza do diagnóstico, procure seu médico.</strong></h4>

  <!--<p><strong>Quanto maior a base de casos, melhor a análise. Se souberem de bases melhores, enviem para:-->
  <!--contato@birmind.com.br</strong></p>-->

  <p><strong>Bibliografia:</strong></p>
  <ul>
    <li>Lippi, G. & Plebani,M. (2020) Laboratory abnormalities in patients with Covid-2019 infection. Clinical
Chemistry and Laboratory Medicine (CCLM), 0(0), pp-, Retrieved 19 Mar.2020, from doi: 10.1515/cclm2020-0198.
      <a href="https://www.degruyter.com/view/journals/cclm/ahead-of-print/article-10.1515-cclm-2020-0198/
      article-10.1515-cclm-2020-0198.xml">-> (Link)</a></li>
    <li>Zhou,F., Yu, T.,Du, R.,Fan,G.,Liu,Y.,Liu,Z...&Guan,L. (2020) Clinical course and risk factors for mortality of
adult inpatients with Covid-19 in Wuhan, China: a retrospective cohort study. The Lancet.
      <a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30566-3/fulltext">-> (Link)</a></li>
  </ul>

<div class="col-md-8">

  <h1 align="center">
    COVID19 DIAGNOSE
  </h1>

  <p>Esta aplicação tem o intuito de fazer uma análise prévia de testes laboratoriais para indicar a presença
  ou não de COVID19, permitindo economizar testes e só utilizá-los em casos necessários.</p>

  <p>O sistema foi modelado considerando o tratamento da base do Hospital Israelita Albert Einstein:
    <a href="https://www.kaggle.com/dataset/e626783d4672f182e7870b1bbe75fae66bdfb232289da0a61f08c2ceb01cab01/data">link</a></p>

  <p>A lógica foi a seguinte:</p>
    <ul class="list-group">
      <li class="list-group-item list-group-item-dark">  Limpeza da base (retirada de colunas vazias/com
        poucos dados</li>
      <li class="list-group-item list-group-item-dark">  Conversão de categorias para sequência numérica
        (a,b.c vira 1,2,3 por exemplo)</li>
      <li class="list-group-item list-group-item-dark">  Avaliação estatística de correlação entre análises de
        laboratório e presença ou não de COVID19</li>
      <li class="list-group-item list-group-item-dark">  Separação das top15 variáveis para treinamento de
        uma rede neural</li>
      <li class="list-group-item list-group-item-dark">  Treinamento da rede e testes de eficácia</li>
      <li class="list-group-item list-group-item-dark">  Criação de uma aplicação simples para que o usuário
        insira dados laboratoriais e receba a resposta o resultado de positivo ou negativo para COVID19</li>
    </ul>

  <p>Os resultados obtidos estão a seguir, bem como um espaço para você colocar os dados de
  laboratório e o sistema diagnosticar a presença ou não de COVID19.</p>

  <h4><strong>Variáveis mais relevantes:</strong></h4>
  <p>(quanto cada uma das 15 principais variáveis influencia em resultados positivos para COVID-19)</p>
  <table class="table">
    {% for i,j in top15 %}
      <tr>
        <td>{{ i }}</td>
        <td style="color:blue">{{ j|floatformat:2 }} %</td>
      </tr>
    {% endfor %}
  </table>

  <p><Strong>Modelo estatístico (ExtraTreeClassifier):</Strong> <a style="color:blue">{{ modelo_ft_import }}</a></p>

  <h4><strong>Rede neural treinada:</strong></h4>
  <p>(a partir dos dados de exames laboratoriais, qual seria o provável resultado do teste de COVID-19)</p>

  <p><strong>Modelo da rede (MLPClassifier):</strong> <a style="color:blue">{{ modelo_mlpc }}</a></p>

  <p><strong>Acurácia da rede neural:</strong> <a style="color:blue">{{ acuracia }} %</a></p>

  <h4><strong>Validações</strong></h4>
  <p>De modo a validar a precisão, 2 testes são feitos abaixo. Se os valores diferirem do título, aperte f5 para
  um novo treinamento da rede neural.</p>
  <p><strong>Validação 1 - NEGATIVO</strong></p>
  <p> dados: {{ dados_neg }}</p>
  <p> Resultado: <strong style="color:blue">{{ result_neg }}</strong></p>

  <p><strong>Validação 2 - POSITIVO</strong></p>
  <p> dados: {{ dados_pos }}</p>
  <p> Resultado: <strong style="color:blue">{{ result_pos }}</strong></p>

</div>
<div class="col-md-4 sticky" style="text-align:center">

  <h2>Diagnóstico COVID-19</h2>
  <p>números com casas decimais, utilizar .(ponto) e não ,(vírgula)</p>

  <form action="{% url 'frontend:predict' %}" method="post">
  {% csrf_token %}

    {% for i in top15_names %}
    <label>{{ i }}</label><br>
    <input type="text" name="question_id{{ forloop.counter }}" value="question_id{{ forloop.counter }}"><br>
    {% endfor %}
    <input type="submit" value="Calcular">

  </form>



</div>

</div>

</body>
</html>

frontend/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>COVID19 MONITOR</title>
  <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>

<style>
  .button {
  font: bold 32px Arial;
  text-decoration: none;
  background-color: rgba(200,180,120,0.7);
  color: #333333;
  padding: 2px 6px 2px 6px;
  border-top: 1px solid #CCCCCC;
  border-right: 1px solid #333333;
  border-bottom: 1px solid #333333;
  border-left: 1px solid #CCCCCC;
}
</style>

<div id="page-wrap">

  <div style="text-align:center">
    <a class="button" href="/">Página Inicial</a>
    <a class="button" href="/diagnose">Diagnóstico COVID</a>
    <a class="button" href="/simulation">Simulador Contágio</a>
  </div>

  <h1 align="center">
    Report de casos de COVID19
  </h1>
  {% if last_update %}
    <h6 style="text-align: right"> *Última atualização: {{ last_update }}</h6>
  {% endif %}
  {{ chart_1|safe }}


  <p>
    O gráfico acima mostra a evolução dos casos confirmados para diferentes
    países a partir do dia em que atingiram 50 casos. Esta métrica é utilizada
    para comparar as curvas na mesma janela de tempo
  </p>

  {{ chart_2|safe }}

  <p>
    O gráfico acima mostra a velocidade de progressão de contaminação para
    diferentes países através da quantidade de dias necessários para dobrar o
    número de casos. Esta métrica é observada ao longo do tempo e quanto
    menor o valor, mais rápida é a contaminação
  </p>

  {{ chart_3|safe }}

  <p>
    O gráfico acima mostra a velocidade de progressão de contaminação numa
    visão acumulada a partir do momento 0. Assim, o número no eixo vertical
    corresponde à taxa de multiplicação de casos num determinado período, em
    relação ao ponto 0
  </p>

  {{ chart_4|safe }}

  <p>
    O gráfico representa a projeção de casos para o Brasil caso ele seguisse
    a progressão de contaminação de 3 países selecionados: Itália, China e
    Coréia do Sul
  </p>

    {{ chart_5|safe }}

  <p>
    Este gráfico mostra a comparação entre os casos acumulados e novos casos
    no mundo, para sabermos se estamos controlando o surto
  </p>

    {{ chart_6|safe }}

  <p>
    Este gráfico mostra a comparação entre os casos acumulados e novos casos
    no Brasil, para sabermos se estamos controlando o surto
  </p>

</div>

</body>
</html>

frontend/templates/simulation.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Simulation COVID19</title>
  <script src="{% static 'js/p5.min.js' %}"></script>
  <script src="{% static 'js/particles.js' %}"></script>
  <script src="{% static 'js/covid.js' %}"></script>
</head>
<body>

{#<style>#}
{#    .button2 {#}
{#  font: bold 32px Arial;#}
{#  text-decoration: none;#}
{#  background-color: rgba(200,180,120,0.7);#}
{#  color: #333333;#}
{#  padding: 2px 6px 2px 6px;#}
{#  border-top: 1px solid #CCCCCC;#}
{#  border-right: 1px solid #333333;#}
{#  border-bottom: 1px solid #333333;#}
{#  border-left: 1px solid #CCCCCC;#}

{#</style>#}
{##}
{#  <div style="text-align:center">#}
{#    <a class="button2" href="/">Página Inicial</a>#}
{#    <a class="button2" href="/diagnose">Diagnóstico COVID</a>#}
{#    <a class="button2" href="/simulation">Simulador Contágio</a>#}
{#  </div>#}

<div id="container">

</div>

</body>
</html>